// ---------------- [ File: bitcoin-fuzz/src/lib.rs ]
#![feature(test)]

#[macro_use] mod imports; use imports::*;

x!{fuzz_addition_overflow}
x!{fuzz_addrman}
x!{fuzz_asmap_direct}
x!{fuzz_asmap}
x!{fuzz_autofile}
x!{fuzz_banman}
x!{fuzz_base_encode_decode}
x!{fuzz_bech32}
x!{fuzz_block_header}
x!{fuzz_block}
x!{fuzz_blockfilter}
x!{fuzz_bloom_filter}
x!{fuzz_buffered_file}
x!{fuzz_chain}
x!{fuzz_checkqueue}
x!{fuzz_coins_view}
x!{fuzz_connman}
x!{fuzz_crypto_aes256}
x!{fuzz_crypto_aes256cbc}
x!{fuzz_crypto_chacha20_poly1305_aead}
x!{fuzz_crypto_chacha20}
x!{fuzz_crypto_common}
x!{fuzz_crypto_hkdf_hmac_sha256_l32}
x!{fuzz_crypto_poly1305}
x!{fuzz_crypto}
x!{fuzz_cuckoocache}
x!{fuzz_decode_tx}
x!{fuzz_descriptor_parse}
x!{fuzz_deserialize}
x!{fuzz_eval_script}
x!{fuzz_fee_rate}
x!{fuzz_fees}
x!{fuzz_flatfile}
x!{fuzz_float}
x!{fuzz_fuzzeddataprovider}
x!{fuzz_golomb_rice}
x!{fuzz_hex}
x!{fuzz_http_request}
x!{fuzz_i2p}
x!{fuzz_integer}
x!{fuzz_key_io}
x!{fuzz_key}
x!{fuzz_kitchen_sink}
x!{fuzz_load_external_block_file}
x!{fuzz_locale}
x!{fuzz_merkleblock}
x!{fuzz_message}
x!{fuzz_muhash}
x!{fuzz_multiplication_overflow}
x!{fuzz_net_permissions}
x!{fuzz_net}
x!{fuzz_netaddress}
x!{fuzz_netbase_dns_lookup}
x!{fuzz_node_eviction}
x!{fuzz_p2p_transport_serialization}
x!{fuzz_parse_hd_keypath}
x!{fuzz_parse_iso8601}
x!{fuzz_parse_numbers}
x!{fuzz_parse_script}
x!{fuzz_parse_univalue}
x!{fuzz_policy_estimator_io}
x!{fuzz_policy_estimator}
x!{fuzz_pow}
x!{fuzz_prevector}
x!{fuzz_primitives_transaction}
x!{fuzz_process_message}
x!{fuzz_process_messages}
x!{fuzz_protocol}
x!{fuzz_psbt}
x!{fuzz_random}
x!{fuzz_rbf}
x!{fuzz_rolling_bloom_filter}
x!{fuzz_rpc}
x!{fuzz_script_assets_test_minimizer}
x!{fuzz_script_consensus}
x!{fuzz_script_descriptor_cache}
x!{fuzz_script_flags}
x!{fuzz_script_interpreter}
x!{fuzz_script_ops}
x!{fuzz_script_sigcache}
x!{fuzz_script_sign}
x!{fuzz_script}
x!{fuzz_scriptnum_ops}
x!{fuzz_secp256k1_ec_seckey_import_export_der}
x!{fuzz_secp256k1_ecdsa_signature_parse_der_lax}
x!{fuzz_signature_checker}
x!{fuzz_signet}
x!{fuzz_socks5}
x!{fuzz_span}
x!{fuzz_spanparsing}
x!{fuzz_string}
x!{fuzz_strprintf}
x!{fuzz_system}
x!{fuzz_timedata}
x!{fuzz_torcontrol}
x!{fuzz_transaction}
x!{fuzz_tx_in}
x!{fuzz_tx_out}
x!{fuzz_tx_pool}
x!{fuzz_txrequest}
x!{fuzz_util}
x!{fuzz_utxo_snapshot}
x!{fuzz_validation_load_mempool}
x!{fuzz_versionbits}
x!{fuzz_test_fuzz}

pub struct InitializerList<T> { p: std::marker::PhantomData<T> }
