// ---------------- [ File: bitcoin-syscall/src/linux_syscalls.rs ]
crate::ix!();

/**
  | This list of syscalls in LINUX_SYSCALLS is only
  | used to map syscall numbers to syscall names in
  | order to be able to print user friendly error
  | messages which include the syscall name in
  | addition to the syscall number.
  |
  | Example output in case of a syscall violation
  | where the syscall is present in LINUX_SYSCALLS:
  |
  | ```
  |
  | 2021-06-09T12:34:56Z ERROR: The syscall
  | "execve" (syscall number 59) is not allowed by
  | the syscall sandbox in thread "msghand". Please
  | report.
  |
  | ```
  |
  | Example output in case of a syscall violation
  | where the syscall is not present in
  | LINUX_SYSCALLS:
  |
  | ```
  | 2021-06-09T12:34:56Z ERROR: The syscall
  | "*unknown*" (syscall number 314) is not allowed
  | by the syscall sandbox in thread
  | "msghand". Please report.
  |
  | ``
  |
  | LINUX_SYSCALLS contains two types of syscalls:
  |
  | 1.) Syscalls that are present under all
  |     architectures or relevant Linux kernel
  |     versions for which we support the syscall
  |     sandbox feature (currently only Linux
  |     x86-64). Examples include read, write,
  |     open, close, etc.
  |
  | 2.) Syscalls that are present under a subset of
  |     architectures or relevant Linux kernel
  |     versions for which we support the syscall
  |     sandbox feature. This type of syscalls
  |     should be added to LINUX_SYSCALLS
  |     conditional on availability like in the
  |     following example:
  |
  |   ...
  |   #if defined(__NR_arch_dependent_syscall)
  |       {__NR_arch_dependent_syscall, "arch_dependent_syscall"},
  |   #endif // defined(__NR_arch_dependent_syscall)
  |   ...
  */
pub const LINUX_SYSCALLS: HashMap<u32, &'static str> = hashmap!{
    __NR_accept                 => "accept",
    __NR_accept4                => "accept4",
    __NR_access                 => "access",
    __NR_acct                   => "acct",
    __NR_add_key                => "add_key",
    __NR_adjtimex               => "adjtimex",
    __NR_afs_syscall            => "afs_syscall",
    __NR_alarm                  => "alarm",
    __NR_arch_prctl             => "arch_prctl",
    __NR_bind                   => "bind",
    __NR_bpf                    => "bpf",
    __NR_brk                    => "brk",
    __NR_capget                 => "capget",
    __NR_capset                 => "capset",
    __NR_chdir                  => "chdir",
    __NR_chmod                  => "chmod",
    __NR_chown                  => "chown",
    __NR_chroot                 => "chroot",
    __NR_clock_adjtime          => "clock_adjtime",
    __NR_clock_getres           => "clock_getres",
    __NR_clock_gettime          => "clock_gettime",
    __NR_clock_nanosleep        => "clock_nanosleep",
    __NR_clock_settime          => "clock_settime",
    __NR_clone                  => "clone",
    __NR_clone3                 => "clone3",
    __NR_close                  => "close",
    __NR_connect                => "connect",
    __NR_copy_file_range        => "copy_file_range",
    __NR_creat                  => "creat",
    __NR_create_module          => "create_module",
    __NR_delete_module          => "delete_module",
    __NR_dup                    => "dup",
    __NR_dup2                   => "dup2",
    __NR_dup3                   => "dup3",
    __NR_epoll_create           => "epoll_create",
    __NR_epoll_create1          => "epoll_create1",
    __NR_epoll_ctl              => "epoll_ctl",
    __NR_epoll_ctl_old          => "epoll_ctl_old",
    __NR_epoll_pwait            => "epoll_pwait",
    __NR_epoll_wait             => "epoll_wait",
    __NR_epoll_wait_old         => "epoll_wait_old",
    __NR_eventfd                => "eventfd",
    __NR_eventfd2               => "eventfd2",
    __NR_execve                 => "execve",
    __NR_execveat               => "execveat",
    __NR_exit                   => "exit",
    __NR_exit_group             => "exit_group",
    __NR_faccessat              => "faccessat",
    __NR_fadvise64              => "fadvise64",
    __NR_fallocate              => "fallocate",
    __NR_fanotify_init          => "fanotify_init",
    __NR_fanotify_mark          => "fanotify_mark",
    __NR_fchdir                 => "fchdir",
    __NR_fchmod                 => "fchmod",
    __NR_fchmodat               => "fchmodat",
    __NR_fchown                 => "fchown",
    __NR_fchownat               => "fchownat",
    __NR_fcntl                  => "fcntl",
    __NR_fdatasync              => "fdatasync",
    __NR_fgetxattr              => "fgetxattr",
    __NR_finit_module           => "finit_module",
    __NR_flistxattr             => "flistxattr",
    __NR_flock                  => "flock",
    __NR_fork                   => "fork",
    __NR_fremovexattr           => "fremovexattr",
    __NR_fsetxattr              => "fsetxattr",
    __NR_fstat                  => "fstat",
    __NR_fstatfs                => "fstatfs",
    __NR_fsync                  => "fsync",
    __NR_ftruncate              => "ftruncate",
    __NR_futex                  => "futex",
    __NR_futimesat              => "futimesat",
    __NR_get_kernel_syms        => "get_kernel_syms",
    __NR_get_mempolicy          => "get_mempolicy",
    __NR_get_robust_list        => "get_robust_list",
    __NR_get_thread_area        => "get_thread_area",
    __NR_getcpu                 => "getcpu",
    __NR_getcwd                 => "getcwd",
    __NR_getdents               => "getdents",
    __NR_getdents64             => "getdents64",
    __NR_getegid                => "getegid",
    __NR_geteuid                => "geteuid",
    __NR_getgid                 => "getgid",
    __NR_getgroups              => "getgroups",
    __NR_getitimer              => "getitimer",
    __NR_getpeername            => "getpeername",
    __NR_getpgid                => "getpgid",
    __NR_getpgrp                => "getpgrp",
    __NR_getpid                 => "getpid",
    __NR_getpmsg                => "getpmsg",
    __NR_getppid                => "getppid",
    __NR_getpriority            => "getpriority",
    __NR_getrandom              => "getrandom",
    __NR_getresgid              => "getresgid",
    __NR_getresuid              => "getresuid",
    __NR_getrlimit              => "getrlimit",
    __NR_getrusage              => "getrusage",
    __NR_getsid                 => "getsid",
    __NR_getsockname            => "getsockname",
    __NR_getsockopt             => "getsockopt",
    __NR_gettid                 => "gettid",
    __NR_gettimeofday           => "gettimeofday",
    __NR_getuid                 => "getuid",
    __NR_getxattr               => "getxattr",
    __NR_init_module            => "init_module",
    __NR_inotify_add_watch      => "inotify_add_watch",
    __NR_inotify_init           => "inotify_init",
    __NR_inotify_init1          => "inotify_init1",
    __NR_inotify_rm_watch       => "inotify_rm_watch",
    __NR_io_cancel              => "io_cancel",
    __NR_io_destroy             => "io_destroy",
    __NR_io_getevents           => "io_getevents",
    __NR_io_setup               => "io_setup",
    __NR_io_submit              => "io_submit",
    __NR_ioctl                  => "ioctl",
    __NR_ioperm                 => "ioperm",
    __NR_iopl                   => "iopl",
    __NR_ioprio_get             => "ioprio_get",
    __NR_ioprio_set             => "ioprio_set",
    __NR_kcmp                   => "kcmp",
    __NR_kexec_file_load        => "kexec_file_load",
    __NR_kexec_load             => "kexec_load",
    __NR_keyctl                 => "keyctl",
    __NR_kill                   => "kill",
    __NR_lchown                 => "lchown",
    __NR_lgetxattr              => "lgetxattr",
    __NR_link                   => "link",
    __NR_linkat                 => "linkat",
    __NR_listen                 => "listen",
    __NR_listxattr              => "listxattr",
    __NR_llistxattr             => "llistxattr",
    __NR_lookup_dcookie         => "lookup_dcookie",
    __NR_lremovexattr           => "lremovexattr",
    __NR_lseek                  => "lseek",
    __NR_lsetxattr              => "lsetxattr",
    __NR_lstat                  => "lstat",
    __NR_madvise                => "madvise",
    __NR_mbind                  => "mbind",
    __NR_membarrier             => "membarrier",
    __NR_memfd_create           => "memfd_create",
    __NR_migrate_pages          => "migrate_pages",
    __NR_mincore                => "mincore",
    __NR_mkdir                  => "mkdir",
    __NR_mkdirat                => "mkdirat",
    __NR_mknod                  => "mknod",
    __NR_mknodat                => "mknodat",
    __NR_mlock                  => "mlock",
    __NR_mlock2                 => "mlock2",
    __NR_mlockall               => "mlockall",
    __NR_mmap                   => "mmap",
    __NR_modify_ldt             => "modify_ldt",
    __NR_mount                  => "mount",
    __NR_move_pages             => "move_pages",
    __NR_mprotect               => "mprotect",
    __NR_mq_getsetattr          => "mq_getsetattr",
    __NR_mq_notify              => "mq_notify",
    __NR_mq_open                => "mq_open",
    __NR_mq_timedreceive        => "mq_timedreceive",
    __NR_mq_timedsend           => "mq_timedsend",
    __NR_mq_unlink              => "mq_unlink",
    __NR_mremap                 => "mremap",
    __NR_msgctl                 => "msgctl",
    __NR_msgget                 => "msgget",
    __NR_msgrcv                 => "msgrcv",
    __NR_msgsnd                 => "msgsnd",
    __NR_msync                  => "msync",
    __NR_munlock                => "munlock",
    __NR_munlockall             => "munlockall",
    __NR_munmap                 => "munmap",
    __NR_name_to_handle_at      => "name_to_handle_at",
    __NR_nanosleep              => "nanosleep",
    __NR_newfstatat             => "newfstatat",
    __NR_nfsservctl             => "nfsservctl",
    __NR_open                   => "open",
    __NR_open_by_handle_at      => "open_by_handle_at",
    __NR_openat                 => "openat",
    __NR_pause                  => "pause",
    __NR_perf_event_open        => "perf_event_open",
    __NR_personality            => "personality",
    __NR_pipe                   => "pipe",
    __NR_pipe2                  => "pipe2",
    __NR_pivot_root             => "pivot_root",

    #[cfg(__NR_pkey_alloc)]
    __NR_pkey_alloc             => "pkey_alloc",

    #[cfg(__NR_pkey_free)]
    __NR_pkey_free              => "pkey_free",

    #[cfg(__NR_pkey_mprotect)]
    __NR_pkey_mprotect          => "pkey_mprotect",

    __NR_poll                   => "poll",
    __NR_ppoll                  => "ppoll",
    __NR_prctl                  => "prctl",
    __NR_pread64                => "pread64",
    __NR_preadv                 => "preadv",

    #[cfg(__NR_preadv2)]
    __NR_preadv2                => "preadv2",

    __NR_prlimit64              => "prlimit64",
    __NR_process_vm_readv       => "process_vm_readv",
    __NR_process_vm_writev      => "process_vm_writev",
    __NR_pselect6               => "pselect6",
    __NR_ptrace                 => "ptrace",
    __NR_putpmsg                => "putpmsg",
    __NR_pwrite64               => "pwrite64",
    __NR_pwritev                => "pwritev",

    #[cfg(__NR_pwritev2)]
    __NR_pwritev2               => "pwritev2",

    __NR__sysctl                => "_sysctl",
    __NR_query_module           => "query_module",
    __NR_quotactl               => "quotactl",
    __NR_read                   => "read",
    __NR_readahead              => "readahead",
    __NR_readlink               => "readlink",
    __NR_readlinkat             => "readlinkat",
    __NR_readv                  => "readv",
    __NR_reboot                 => "reboot",
    __NR_recvfrom               => "recvfrom",
    __NR_recvmmsg               => "recvmmsg",
    __NR_recvmsg                => "recvmsg",
    __NR_remap_file_pages       => "remap_file_pages",
    __NR_removexattr            => "removexattr",
    __NR_rename                 => "rename",
    __NR_renameat               => "renameat",
    __NR_renameat2              => "renameat2",
    __NR_request_key            => "request_key",
    __NR_restart_syscall        => "restart_syscall",
    __NR_rmdir                  => "rmdir",
    __NR_rt_sigaction           => "rt_sigaction",
    __NR_rt_sigpending          => "rt_sigpending",
    __NR_rt_sigprocmask         => "rt_sigprocmask",
    __NR_rt_sigqueueinfo        => "rt_sigqueueinfo",
    __NR_rt_sigreturn           => "rt_sigreturn",
    __NR_rt_sigsuspend          => "rt_sigsuspend",
    __NR_rt_sigtimedwait        => "rt_sigtimedwait",
    __NR_rt_tgsigqueueinfo      => "rt_tgsigqueueinfo",
    __NR_sched_get_priority_max => "sched_get_priority_max",
    __NR_sched_get_priority_min => "sched_get_priority_min",
    __NR_sched_getaffinity      => "sched_getaffinity",
    __NR_sched_getattr          => "sched_getattr",
    __NR_sched_getparam         => "sched_getparam",
    __NR_sched_getscheduler     => "sched_getscheduler",
    __NR_sched_rr_get_interval  => "sched_rr_get_interval",
    __NR_sched_setaffinity      => "sched_setaffinity",
    __NR_sched_setattr          => "sched_setattr",
    __NR_sched_setparam         => "sched_setparam",
    __NR_sched_setscheduler     => "sched_setscheduler",
    __NR_sched_yield            => "sched_yield",
    __NR_seccomp                => "seccomp",
    __NR_security               => "security",
    __NR_select                 => "select",
    __NR_semctl                 => "semctl",
    __NR_semget                 => "semget",
    __NR_semop                  => "semop",
    __NR_semtimedop             => "semtimedop",
    __NR_sendfile               => "sendfile",
    __NR_sendmmsg               => "sendmmsg",
    __NR_sendmsg                => "sendmsg",
    __NR_sendto                 => "sendto",
    __NR_set_mempolicy          => "set_mempolicy",
    __NR_set_robust_list        => "set_robust_list",
    __NR_set_thread_area        => "set_thread_area",
    __NR_set_tid_address        => "set_tid_address",
    __NR_setdomainname          => "setdomainname",
    __NR_setfsgid               => "setfsgid",
    __NR_setfsuid               => "setfsuid",
    __NR_setgid                 => "setgid",
    __NR_setgroups              => "setgroups",
    __NR_sethostname            => "sethostname",
    __NR_setitimer              => "setitimer",
    __NR_setns                  => "setns",
    __NR_setpgid                => "setpgid",
    __NR_setpriority            => "setpriority",
    __NR_setregid               => "setregid",
    __NR_setresgid              => "setresgid",
    __NR_setresuid              => "setresuid",
    __NR_setreuid               => "setreuid",
    __NR_setrlimit              => "setrlimit",
    __NR_setsid                 => "setsid",
    __NR_setsockopt             => "setsockopt",
    __NR_settimeofday           => "settimeofday",
    __NR_setuid                 => "setuid",
    __NR_setxattr               => "setxattr",
    __NR_shmat                  => "shmat",
    __NR_shmctl                 => "shmctl",
    __NR_shmdt                  => "shmdt",
    __NR_shmget                 => "shmget",
    __NR_shutdown               => "shutdown",
    __NR_sigaltstack            => "sigaltstack",
    __NR_signalfd               => "signalfd",
    __NR_signalfd4              => "signalfd4",
    __NR_socket                 => "socket",
    __NR_socketpair             => "socketpair",
    __NR_splice                 => "splice",
    __NR_stat                   => "stat",
    __NR_statfs                 => "statfs",
    __NR_statx                  => "statx",
    __NR_swapoff                => "swapoff",
    __NR_swapon                 => "swapon",
    __NR_symlink                => "symlink",
    __NR_symlinkat              => "symlinkat",
    __NR_sync                   => "sync",
    __NR_sync_file_range        => "sync_file_range",
    __NR_syncfs                 => "syncfs",
    __NR_sysfs                  => "sysfs",
    __NR_sysinfo                => "sysinfo",
    __NR_syslog                 => "syslog",
    __NR_tee                    => "tee",
    __NR_tgkill                 => "tgkill",
    __NR_time                   => "time",
    __NR_timer_create           => "timer_create",
    __NR_timer_delete           => "timer_delete",
    __NR_timer_getoverrun       => "timer_getoverrun",
    __NR_timer_gettime          => "timer_gettime",
    __NR_timer_settime          => "timer_settime",
    __NR_timerfd_create         => "timerfd_create",
    __NR_timerfd_gettime        => "timerfd_gettime",
    __NR_timerfd_settime        => "timerfd_settime",
    __NR_times                  => "times",
    __NR_tkill                  => "tkill",
    __NR_truncate               => "truncate",
    __NR_tuxcall                => "tuxcall",
    __NR_umask                  => "umask",
    __NR_umount2                => "umount2",
    __NR_uname                  => "uname",
    __NR_unlink                 => "unlink",
    __NR_unlinkat               => "unlinkat",
    __NR_unshare                => "unshare",
    __NR_uselib                 => "uselib",
    __NR_userfaultfd            => "userfaultfd",
    __NR_ustat                  => "ustat",
    __NR_utime                  => "utime",
    __NR_utimensat              => "utimensat",
    __NR_utimes                 => "utimes",
    __NR_vfork                  => "vfork",
    __NR_vhangup                => "vhangup",
    __NR_vmsplice               => "vmsplice",
    __NR_vserver                => "vserver",
    __NR_wait4                  => "wait4",
    __NR_waitid                 => "waitid",
    __NR_write                  => "write",
    __NR_writev                 => "writev",
};
